services:
  postgres:
    image: 'postgres:latest'
    container_name: tab-identity_and_tenant-dev
    environment:
      - 'POSTGRES_DB=identity_and_tenant'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

