server:
  port: 8681
spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/identity_and_tenant
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    activate:
      on-profile: dev

google-firebase:
  api-base-url: https://identitytoolkit.googleapis.com/v1/accounts
  service-uid: identity-and-tenant-svc

tab-services:
  admin-frontend:
    base-url: http://localhost:4200
  notifications:
    base-url: "http://localhost:8381/notifications-service"

logging:
  level:
    root: DEBUG